# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=100, verbose_name='\u987a\u5e8f')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u8df3\u8f6c\u5730\u5740')),
                ('image', models.ImageField(max_length=200, upload_to='upload/global/images/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u6fc0\u6d3b\u7801')),
                ('email', models.EmailField(max_length=25, verbose_name='\u90ae\u7bb1')),
                ('code_type', models.IntegerField(choices=[(1, '\u6fc0\u6d3b\u90ae\u7bb1'), (2, '\u5fd8\u8bb0\u5bc6\u7801')], verbose_name='\u9a8c\u8bc1\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
            },
        ),
    ]
