# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282\u4fe1\u606f',
                'verbose_name_plural': '\u7ae0\u8282\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('desc', models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u7b80\u4ecb')),
                ('degree', models.IntegerField(choices=[(1, '\u521d\u7ea7'), (2, '\u4e2d\u7ea7'), (3, '\u9ad8\u7ea7')], verbose_name='\u8bfe\u7a0b\u96be\u5ea6')),
                ('learn_times', models.IntegerField(verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u5206\u949f\u6570\uff09')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('student_nums', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('detail', models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5')),
                ('cover_image', models.ImageField(max_length=300, upload_to='upload/courses/images/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('course_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='\u8bfe\u7a0b\u673a\u6784')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='\u4e3b\u8bb2\u8001\u5e08')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u4fe1\u606f',
                'verbose_name_plural': '\u8bfe\u7a0b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8d44\u6e90\u540d\u79f0')),
                ('file', models.FileField(max_length=200, upload_to='upload/courses/resources/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('url', models.URLField(default='', max_length=300, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='\u6240\u5c5e\u7ae0\u8282')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u4fe1\u606f',
                'verbose_name_plural': '\u89c6\u9891\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u6240\u5c5e\u8bfe\u7a0b'),
        ),
    ]
