# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.IntegerField(choices=[(1, '\u521d\u7ea7'), (2, '\u4e2d\u7ea7'), (3, '\u9ad8\u7ea7')], verbose_name='\u8bfe\u7a0b\u7684\u96be\u5ea6'),
        ),
    ]
