# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170612_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u7ae0\u8282\u540d\u79f0'),
        ),
    ]
