# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='\u57ce\u5e02\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02\u4fe1\u606f',
                'verbose_name_plural': '\u57ce\u5e02\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('cover_image', models.ImageField(max_length=200, upload_to='upload/organizations/images/%Y/%m', verbose_name='\u673a\u6784\u5c01\u9762\u56fe')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('desc', models.TextField(verbose_name='\u673a\u6784\u4ecb\u7ecd')),
                ('org_type', models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='', max_length=5, verbose_name='\u673a\u6784\u7c7b\u522b')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u673a\u6784\u5730\u5740')),
                ('student_nums', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u4eba\u6570')),
                ('course_nums', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CityDict', verbose_name='\u6240\u5728\u57ce\u5e02')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u673a\u6784',
                'verbose_name_plural': '\u6388\u8bfe\u673a\u6784',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('work_years', models.IntegerField(verbose_name='\u5de5\u4f5c\u5e74\u9650')),
                ('work_company', models.CharField(max_length=30, verbose_name='\u5c31\u804c\u516c\u53f8')),
                ('work_position', models.CharField(max_length=10, verbose_name='\u5de5\u4f5c\u804c\u4f4d')),
                ('feature', models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('avatar', models.ImageField(default='upload/teachers/avatars/default.png', upload_to='upload/teachers/avatars/%Y/%m', verbose_name='\u5934\u50cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('org', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='\u6240\u5c5e\u673a\u6784')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u6559\u5e08',
                'verbose_name_plural': '\u6388\u8bfe\u6559\u5e08',
            },
        ),
    ]
