# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-11 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='course_nums',
        ),
    ]
