# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-10 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
    ]
