# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-10 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_course_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='course_nums',
        ),
    ]
